apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: logging
  namespace: openshift-logging
spec:
  managementState: Managed
  outputs:
    - name: default-output
      type: loki
      url: http://logging-loki-gateway-http.openshift-logging.svc:8080
  pipelines:
    - inputRefs:
        - default-input
      outputRefs:
        - default-output
      name: default-pipeline
  serviceAccount:
    name: log-forwarder-sa