apiVersion: v1
kind: Service
metadata:
    name: nginx-helloworld
spec:
    type: LoadBalancer
    selector:
        app: nginx-helloworld
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80